# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20160417_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='blood',
            field=models.CharField(default=b'', max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='hla',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
